# This is a basic workflow to help you get started with Actions

name: siftipub

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  web-deploy:
    name: 🎉 Deploy
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: 🚚 Get latest code
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with: 
           server: ${{ secrets.ftp_server}}
           username: ${{ secrets.ftp_username}}
           password: ${{ secrets.ftp_password }}
           server_dir: ${{ secrets.ftp_server_dir}}
           local_dir: ./web-edition/
           protocol: ftps
           port: 22


